### ISSUE TITLE
Melhorias na página de inscrição

### ISSUE THREAD

**Issue by RafaelFunchal** [wpbrasil/slack-invite-automation#11]
O @claudiosanches propos isso no Slack ontem e estou abrindo essa issue para documentar o processo:

>estou querendo mudar a página https://slack-wpbrasil.herokuapp.com/
> Primeiro de tudo remover as qualidades do slack lá, não precisa justificar porque estmos usando.
> Então usar o texto para explicar o que fazemos aqui.
> Depois no final ter dois botões.
> Um vermelho do lado esquerdo dizendo "Quero participar e ajudar a comunidade", assim quando clica permite entrar com o e-mail.
> E outro botão azul dizendo "Quero ajuda com um problema no WordPress" e assim quando clica vai para o fórum.

**Comment by RafaelFunchal** [comment]
@mariovalney o Claudio comentou que você havia enviado uma proposta de texto muito boa, porém, isso acabou sumindo.

Você poderia se inspirar novamente? :P

**Comment by mariovalney** [comment]
Foi algo mais ou menos assim:

**Para que serve o Slack da Comunidade WordPress Brasil?**

- Discutir sobre os eventos da Comunidade (meetups e WordCamps) e sua organização.
- Discutir sobre **como ajudar respondendo perguntas** no Fórum de Suporte.
- Discutir sobre **como ajudar com as traduções** do Core e Plugins do WordPress.
- Discutir sobre novidades da Comunidade internacional e do Core do WordPress.
- Avisos e comunicados para todos que participam como voluntários.
- Divulgação de plugins 100% open source para ajudar a Comunidade.
- Discussão sobre os projetos da Comunidade como o Framework Odin.

**Comment by leobaiano** [comment]
Qual a ideia daquele botão `quero participar e ajudar a comunidade`?
