### ISSUE TITLE
Adicionar normalize.css

### ISSUE THREAD

**Issue by eduardozulian** [wpbrasil/slack-invite-automation#9]
Tou querendo colocar o normalize.css pra padronizarmos certas coisas ali dentro. Dito isso, pergunta simples pros iniciados: qualé a melhor pasta pra colocarmos isso?

**Comment by valeriosouza** [comment]
Pra que? Isso é só uma pagina de convite. Não precisa viajar tanto

**Comment by eduardozulian** [comment]
Por que não? Causará algum mal?

**Comment by valeriosouza** [comment]
Porque sim?

**Comment by eduardozulian** [comment]
Se eu for seguir pela afirmação de que é apenas uma página de convite, temos alguns problemas então com alguns desses PR que fiz. Afinal, tudo que fiz foi, basicamente, padronizar: não havia a necessidade de separar arquivos ou até mesmo de criar um `.css` específico. 

A proposta era, na real, termos algum pequeno padrão – e aqui até edito, não precisa necessariamente ser o normalize.css, mas algo que defina apenas coisas simples como altura de linha, tamanho de fonte etc. Foi basicamente o que fiz nos outros PR. Ser "apenas uma página de convite" não me parece um bom motivo pra invalidar a parada. Discutamos, então.
